name: Bug report
description: Report a bug and help improve the plugin
title: "[BUG] Short description of the bug"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug. Include any relevant details.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step description.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Notice that '...'
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if available.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment Information
      description: Environment Information
      value: |
        - **Plugin Version**: [e.g., 1.0.0]
        - **Obsidian Version**: [e.g., v1.3.2]
        - **Operating System**: [e.g., Windows 10]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Required for bug reproduction
      value: |
        - Please attach a video showing the issue
        - Please attach a sample vault where the issue can be reproduced
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I attached a video showing the issue
          required: true
        - label: I attached a sample vault where the issue can be reproduced
          required: true
        - label: I have tested the issue with the latest version
          required: true
        - label: I have checked for existing issues
          required: true
